apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: todo-app
  namespace: argocd
spec:
  project: default
  source:
    # <oci-registry>/<chart-name>
    repoURL: oci://registry.gitlab.com/jerrybai/todo-gcp/todo-chart
    # Chart 版本号
    targetRevision: "99.99.99-latest"
    # Chart 名称
    chart: todo-chart

  destination:
    server: https://kubernetes.default.svc
    namespace: todo-ns
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m